# версия Docker Compose
version: '3.8'

# имена и описания контейнеров, которые должны быть развёрнуты
services:
  # описание контейнера db
  db:
    # образ, из которого должен быть запущен контейнер
    image: postgres:13.7-alpine
    # volume и связанная с ним директория в контейнере
    volumes:
      - /var/lib/postgresql/data/
    # переменные окружения
    environment:
      - POSTGRES_DB=trainee
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot


  java-trainee:
    build: .
    image: java-trainee
    container_name: trainee
    ports:
      - "8080:8080"
    # "зависит от",
    depends_on:
      - db
    # переменные окружения
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/trainee